# Generated by Django 3.2.5 on 2021-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Ação', 'Ação'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Aventura', 'Aventura'), ('Terror', 'Terror'), ('Ciêntifico', 'Ciêntifico'), ('Romance', 'Romance'), ('Suspence', 'Suspence'), ('Musical', 'Musical')], max_length=10)),
                ('avaliacao', models.IntegerField()),
                ('assistido', models.CharField(max_length=10)),
                ('imagem', models.CharField(max_length=200)),
            ],
        ),
    ]
