# Generated by Django 3.2.5 on 2021-07-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriado',
            name='imagemFile',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
