# Generated by Django 3.2.5 on 2021-07-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriado', '0003_alter_seriado_imagemfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriado',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='seriado',
            name='imagemFile',
            field=models.FileField(default='#', upload_to='seriados'),
        ),
    ]
