# Generated by Django 3.2.5 on 2021-07-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seriado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('imagem', models.CharField(max_length=200)),
                ('seriado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriado.seriado')),
            ],
        ),
    ]
