# Generated by Django 3.2.5 on 2021-07-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='imagem',
        ),
        migrations.AddField(
            model_name='temporada',
            name='imagemFile',
            field=models.FileField(default='#', upload_to='temporadas'),
        ),
    ]
